# Generated by Django 4.2.5 on 2023-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
