# Generated by Django 4.2.5 on 2023-10-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='isUpdated',
            field=models.BooleanField(default=1),
        ),
    ]
