# Generated by Django 4.2.5 on 2023-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_events_isupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.AddField(
            model_name='events',
            name='categories',
            field=models.ManyToManyField(to='events.category'),
        ),
    ]
