# Generated by Django 4.2.5 on 2023-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_events_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='categories',
            field=models.ManyToManyField(to='events.category'),
        ),
    ]
