# Generated by Django 4.2.5 on 2023-10-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_events_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='isHome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
