# Generated by Django 4.2.5 on 2023-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_uploadmodel_alter_events_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
