# Generated by Django 4.2.5 on 2023-11-15 14:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_events_imageurl_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
